// Code generated by MockGen. DO NOT EDIT.
// Source: selector.go

// Package setuptest is a generated GoMock package.
package setuptest

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockChainNetworkExistingSelector is a mock of ChainNetworkExistingSelector interface
type MockChainNetworkExistingSelector struct {
	ctrl     *gomock.Controller
	recorder *MockChainNetworkExistingSelectorMockRecorder
}

// MockChainNetworkExistingSelectorMockRecorder is the mock recorder for MockChainNetworkExistingSelector
type MockChainNetworkExistingSelectorMockRecorder struct {
	mock *MockChainNetworkExistingSelector
}

// NewMockChainNetworkExistingSelector creates a new mock instance
func NewMockChainNetworkExistingSelector(ctrl *gomock.Controller) *MockChainNetworkExistingSelector {
	mock := &MockChainNetworkExistingSelector{ctrl: ctrl}
	mock.recorder = &MockChainNetworkExistingSelectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockChainNetworkExistingSelector) EXPECT() *MockChainNetworkExistingSelectorMockRecorder {
	return m.recorder
}

// Select mocks base method
func (m *MockChainNetworkExistingSelector) Select(chain, network, receiver string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", chain, network, receiver)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select
func (mr *MockChainNetworkExistingSelectorMockRecorder) Select(chain, network, receiver interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockChainNetworkExistingSelector)(nil).Select), chain, network, receiver)
}

// MockSimpleSelector is a mock of SimpleSelector interface
type MockSimpleSelector struct {
	ctrl     *gomock.Controller
	recorder *MockSimpleSelectorMockRecorder
}

// MockSimpleSelectorMockRecorder is the mock recorder for MockSimpleSelector
type MockSimpleSelectorMockRecorder struct {
	mock *MockSimpleSelector
}

// NewMockSimpleSelector creates a new mock instance
func NewMockSimpleSelector(ctrl *gomock.Controller) *MockSimpleSelector {
	mock := &MockSimpleSelector{ctrl: ctrl}
	mock.recorder = &MockSimpleSelectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSimpleSelector) EXPECT() *MockSimpleSelectorMockRecorder {
	return m.recorder
}

// Select mocks base method
func (m *MockSimpleSelector) Select(selectorType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", selectorType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select
func (mr *MockSimpleSelectorMockRecorder) Select(selectorType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockSimpleSelector)(nil).Select), selectorType)
}

// MockKeystoreSelector is a mock of KeystoreSelector interface
type MockKeystoreSelector struct {
	ctrl     *gomock.Controller
	recorder *MockKeystoreSelectorMockRecorder
}

// MockKeystoreSelectorMockRecorder is the mock recorder for MockKeystoreSelector
type MockKeystoreSelectorMockRecorder struct {
	mock *MockKeystoreSelector
}

// NewMockKeystoreSelector creates a new mock instance
func NewMockKeystoreSelector(ctrl *gomock.Controller) *MockKeystoreSelector {
	mock := &MockKeystoreSelector{ctrl: ctrl}
	mock.recorder = &MockKeystoreSelectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockKeystoreSelector) EXPECT() *MockKeystoreSelectorMockRecorder {
	return m.recorder
}

// Select mocks base method
func (m *MockKeystoreSelector) Select(keystoreType, keystorePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Select", keystoreType, keystorePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Select indicates an expected call of Select
func (mr *MockKeystoreSelectorMockRecorder) Select(keystoreType, keystorePath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Select", reflect.TypeOf((*MockKeystoreSelector)(nil).Select), keystoreType, keystorePath)
}
