// Code generated by MockGen. DO NOT EDIT.
// Source: sender.go

// Package mailboxtest is a generated GoMock package.
package mailboxtest

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	mailbox "github.com/mailchain/mailchain/internal/mailbox"
	reflect "reflect"
)

// MockSender is a mock of Sender interface
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
}

// MockSenderMockRecorder is the mock recorder for MockSender
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// Send mocks base method
func (m *MockSender) Send(ctx context.Context, to, from, data []byte, signer mailbox.Signer, opts mailbox.SenderOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, to, from, data, signer, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send
func (mr *MockSenderMockRecorder) Send(ctx, to, from, data, signer, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSender)(nil).Send), ctx, to, from, data, signer, opts)
}

// MockSenderOpts is a mock of SenderOpts interface
type MockSenderOpts struct {
	ctrl     *gomock.Controller
	recorder *MockSenderOptsMockRecorder
}

// MockSenderOptsMockRecorder is the mock recorder for MockSenderOpts
type MockSenderOptsMockRecorder struct {
	mock *MockSenderOpts
}

// NewMockSenderOpts creates a new mock instance
func NewMockSenderOpts(ctrl *gomock.Controller) *MockSenderOpts {
	mock := &MockSenderOpts{ctrl: ctrl}
	mock.recorder = &MockSenderOptsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSenderOpts) EXPECT() *MockSenderOptsMockRecorder {
	return m.recorder
}
