// Copyright 2022 Mailchain Ltd
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/envelope/data.proto

package envelope

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Use hosted location where the decryptedhash is the same as the location. Location and encrypted hash are encrypted so only receipient can location and verify the message.
type ZeroX01 struct {
	UIBEncryptedLocationHash []byte   `protobuf:"bytes,1,opt,name=UIBEncryptedLocationHash,proto3" json:"UIBEncryptedLocationHash,omitempty"`
	EncryptedHash            []byte   `protobuf:"bytes,2,opt,name=encryptedHash,proto3" json:"encryptedHash,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *ZeroX01) Reset()         { *m = ZeroX01{} }
func (m *ZeroX01) String() string { return proto.CompactTextString(m) }
func (*ZeroX01) ProtoMessage()    {}
func (*ZeroX01) Descriptor() ([]byte, []int) {
	return fileDescriptor_986908d1a497474f, []int{0}
}

func (m *ZeroX01) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZeroX01.Unmarshal(m, b)
}
func (m *ZeroX01) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZeroX01.Marshal(b, m, deterministic)
}
func (m *ZeroX01) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZeroX01.Merge(m, src)
}
func (m *ZeroX01) XXX_Size() int {
	return xxx_messageInfo_ZeroX01.Size(m)
}
func (m *ZeroX01) XXX_DiscardUnknown() {
	xxx_messageInfo_ZeroX01.DiscardUnknown(m)
}

var xxx_messageInfo_ZeroX01 proto.InternalMessageInfo

func (m *ZeroX01) GetUIBEncryptedLocationHash() []byte {
	if m != nil {
		return m.UIBEncryptedLocationHash
	}
	return nil
}

func (m *ZeroX01) GetEncryptedHash() []byte {
	if m != nil {
		return m.EncryptedHash
	}
	return nil
}

// Use hosted location where the encrypted hash is the same as the location. Location and decrypted hash are encrypted so only receipient can location and verify the message.
type ZeroX02 struct {
	UIBEncryptedLocationHash []byte   `protobuf:"bytes,1,opt,name=UIBEncryptedLocationHash,proto3" json:"UIBEncryptedLocationHash,omitempty"`
	DecryptedHash            []byte   `protobuf:"bytes,2,opt,name=decryptedHash,proto3" json:"decryptedHash,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *ZeroX02) Reset()         { *m = ZeroX02{} }
func (m *ZeroX02) String() string { return proto.CompactTextString(m) }
func (*ZeroX02) ProtoMessage()    {}
func (*ZeroX02) Descriptor() ([]byte, []int) {
	return fileDescriptor_986908d1a497474f, []int{1}
}

func (m *ZeroX02) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZeroX02.Unmarshal(m, b)
}
func (m *ZeroX02) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZeroX02.Marshal(b, m, deterministic)
}
func (m *ZeroX02) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZeroX02.Merge(m, src)
}
func (m *ZeroX02) XXX_Size() int {
	return xxx_messageInfo_ZeroX02.Size(m)
}
func (m *ZeroX02) XXX_DiscardUnknown() {
	xxx_messageInfo_ZeroX02.DiscardUnknown(m)
}

var xxx_messageInfo_ZeroX02 proto.InternalMessageInfo

func (m *ZeroX02) GetUIBEncryptedLocationHash() []byte {
	if m != nil {
		return m.UIBEncryptedLocationHash
	}
	return nil
}

func (m *ZeroX02) GetDecryptedHash() []byte {
	if m != nil {
		return m.DecryptedHash
	}
	return nil
}

// original message format
type ZeroX50 struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	EncryptedURL         []byte   `protobuf:"bytes,2,opt,name=encryptedURL,proto3" json:"encryptedURL,omitempty"`
	DecryptedHash        []byte   `protobuf:"bytes,3,opt,name=decryptedHash,proto3" json:"decryptedHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZeroX50) Reset()         { *m = ZeroX50{} }
func (m *ZeroX50) String() string { return proto.CompactTextString(m) }
func (*ZeroX50) ProtoMessage()    {}
func (*ZeroX50) Descriptor() ([]byte, []int) {
	return fileDescriptor_986908d1a497474f, []int{2}
}

func (m *ZeroX50) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZeroX50.Unmarshal(m, b)
}
func (m *ZeroX50) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZeroX50.Marshal(b, m, deterministic)
}
func (m *ZeroX50) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZeroX50.Merge(m, src)
}
func (m *ZeroX50) XXX_Size() int {
	return xxx_messageInfo_ZeroX50.Size(m)
}
func (m *ZeroX50) XXX_DiscardUnknown() {
	xxx_messageInfo_ZeroX50.DiscardUnknown(m)
}

var xxx_messageInfo_ZeroX50 proto.InternalMessageInfo

func (m *ZeroX50) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ZeroX50) GetEncryptedURL() []byte {
	if m != nil {
		return m.EncryptedURL
	}
	return nil
}

func (m *ZeroX50) GetDecryptedHash() []byte {
	if m != nil {
		return m.DecryptedHash
	}
	return nil
}

func init() {
	proto.RegisterType((*ZeroX01)(nil), "envelope.ZeroX01")
	proto.RegisterType((*ZeroX02)(nil), "envelope.ZeroX02")
	proto.RegisterType((*ZeroX50)(nil), "envelope.ZeroX50")
}

func init() { proto.RegisterFile("internal/envelope/data.proto", fileDescriptor_986908d1a497474f) }

var fileDescriptor_986908d1a497474f = []byte{
	// 179 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xc9, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x4f, 0xcd, 0x2b, 0x4b, 0xcd, 0xc9, 0x2f, 0x48, 0xd5, 0x4f, 0x49,
	0x2c, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0x09, 0x2a, 0x65, 0x73, 0xb1,
	0x47, 0xa5, 0x16, 0xe5, 0x47, 0x18, 0x18, 0x0a, 0x59, 0x71, 0x49, 0x84, 0x7a, 0x3a, 0xb9, 0xe6,
	0x25, 0x17, 0x55, 0x16, 0x94, 0xa4, 0xa6, 0xf8, 0xe4, 0x27, 0x27, 0x96, 0x64, 0xe6, 0xe7, 0x79,
	0x24, 0x16, 0x67, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x04, 0xe1, 0x94, 0x17, 0x52, 0xe1, 0xe2,
	0x4d, 0x85, 0x49, 0x80, 0x35, 0x30, 0x81, 0x35, 0xa0, 0x0a, 0x22, 0x2c, 0x33, 0xa2, 0xd4, 0xb2,
	0x94, 0x54, 0x2c, 0x96, 0xa1, 0x08, 0x2a, 0xe5, 0x42, 0x2d, 0x33, 0x35, 0x10, 0x92, 0xe0, 0x62,
	0x2f, 0x4b, 0x2d, 0x2a, 0xce, 0xcc, 0xcf, 0x03, 0x9b, 0xcd, 0x1a, 0x04, 0xe3, 0x0a, 0x29, 0x71,
	0xf1, 0xc0, 0x9d, 0x18, 0x1a, 0xe4, 0x03, 0x35, 0x09, 0x45, 0x0c, 0xd3, 0x3a, 0x66, 0x2c, 0xd6,
	0x25, 0xb1, 0x81, 0x43, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x56, 0x69, 0x6f, 0xd7, 0x79,
	0x01, 0x00, 0x00,
}
