sequenceDiagram
    participant Sender
    participant Mailchain
    participant AddressIndex
    participant Chain
    
    Sender->>Mailchain: Get Recipient Public Key
    activate Mailchain

    Mailchain->>AddressIndex: Get address transaction
    activate AddressIndex

    AddressIndex->>Mailchain: Transaction Hash
    deactivate AddressIndex

    Mailchain->>Chain: Get transaction
    activate Chain
    Chain->>Mailchain: Transaction data
    deactivate Chain

    Mailchain-->>Sender: 200: Recipient Public Key
    deactivate Mailchain
