sequenceDiagram
    participant S as Sender
    participant MC as Mailchain
    participant SS as SentStore
    participant C as Chain
            
    S->>MC: Sender creates message
    MC->>MC: Add additional fields
    MC->>MC: Encode Message
    MC->>MC: Create message hash - SHA3-256
    MC->>MC: Encrypt message with Recipient Public Key
    MC->>MC: Create encrypted message hash - Murmur3
     
    MC->>SS: PUT: Store encrypted message
    activate SS
    SS->>MC: 201: Created
    deactivate SS

    MC->>MC: Create transaction with encrypted-location and message hash.

    MC->>C: POST: Signed transaction
    C--XMC: Accepted
    
    MC--XS: 200: Accepted
